#!/usr/bin/python3
def raise_exception():
    raise TypeError("Se ha generado una excepci√≥n de tipo TypeError")
